require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/SubjectStub:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/**/*
  inherit_mode:
    merge:
      - Exclude
